<?php
// BEHIX — one-time installer. Creates the database tables, the admin account
// and api/config.php. Locks itself once config.php exists.
define('BX', true);
ini_set('display_errors', '0');
session_start();
require __DIR__ . '/api/lib/core.php';
require __DIR__ . '/api/lib/schema.php';
require __DIR__ . '/api/lib/defaults.php';

$configFile = __DIR__ . '/api/config.php';
// Locked once config.php exists and an admin account has been created.
$locked = false;
if (is_file($configFile)) {
    try {
        $c = bx_config()['db'];
        $chk = new PDO("mysql:host={$c['host']};dbname={$c['name']};charset=utf8mb4", $c['user'], $c['pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
        $locked = (bool) $chk->query("SELECT COUNT(*) FROM users WHERE role = 'admin'")->fetchColumn();
    } catch (Throwable $e) {
        $locked = false;
    }
}
$errors = [];
$done = null;
$manualConfig = null;
if (empty($_SESSION['inst'])) $_SESSION['inst'] = bin2hex(random_bytes(16));

$checks = [
    'نسخه PHP ۷٫۴ یا بالاتر' => version_compare(PHP_VERSION, '7.4.0', '>='),
    'افزونه PDO MySQL' => extension_loaded('pdo_mysql'),
    'افزونه mbstring' => extension_loaded('mbstring'),
    'افزونه cURL (درگاه و پیامک)' => extension_loaded('curl'),
    'پوشه uploads قابل نوشتن' => is_dir(__DIR__ . '/uploads') ? is_writable(__DIR__ . '/uploads') : is_writable(__DIR__),
];

$https = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off');
$guessUrl = ($https ? 'https' : 'http') . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost') . rtrim(str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'] ?? '/')), '/');
$v = function ($k, $d = '') { return htmlspecialchars((string) ($_POST[$k] ?? $d), ENT_QUOTES, 'UTF-8'); };

if (!$locked && $_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!hash_equals($_SESSION['inst'], (string) ($_POST['t'] ?? ''))) $errors[] = 'نشست منقضی شده است؛ صفحه را دوباره باز کنید.';
    $db = ['host' => trim($_POST['db_host'] ?? 'localhost'), 'name' => trim($_POST['db_name'] ?? ''), 'user' => trim($_POST['db_user'] ?? ''), 'pass' => (string) ($_POST['db_pass'] ?? '')];
    $adminName = trim($_POST['admin_name'] ?? '');
    $adminPhone = preg_replace('/\D/', '', en_digits((string) ($_POST['admin_phone'] ?? '')));
    $adminPass = (string) ($_POST['admin_pass'] ?? '');
    $url = rtrim(trim($_POST['url'] ?? $guessUrl), '/');
    if (!$db['name'] || !$db['user']) $errors[] = 'نام و کاربر پایگاه داده را وارد کنید.';
    if (mb_strlen($adminName) < 2) $errors[] = 'نام مدیر را وارد کنید.';
    if (!preg_match('/^09\d{9}$/', $adminPhone)) $errors[] = 'شماره موبایل مدیر معتبر نیست.';
    if (strlen($adminPass) < 8) $errors[] = 'رمز مدیر باید حداقل ۸ کاراکتر باشد.';
    if (!$errors) {
        try {
            $pdo = new PDO("mysql:host={$db['host']};dbname={$db['name']};charset=utf8mb4", $db['user'], $db['pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
        } catch (PDOException $e) {
            $errors[] = 'اتصال به پایگاه داده ناموفق بود: ' . htmlspecialchars($e->getMessage(), ENT_QUOTES, 'UTF-8');
        }
    }
    if (!$errors) {
        $config = ['db' => $db, 'url' => $url, 'secret' => bin2hex(random_bytes(24))];
        $php = "<?php\n// BEHIX configuration — generated by install.php. Keep this file private.\nreturn " . var_export($config, true) . ";\n";
        $pdo->exec("SET time_zone = '+00:00'");
        foreach (bx_schema() as $sql) $pdo->exec($sql);
        if (!is_file($configFile) && !@file_put_contents($configFile, $php)) $manualConfig = $php;
        // core db() reads config.php; load it now so helpers work
        if (!$manualConfig) {
            seed_catalog();
            if (row('SELECT id FROM users WHERE phone = ?', [$adminPhone])) {
                update('users', ['name' => $adminName, 'password_hash' => password_hash($adminPass, PASSWORD_DEFAULT), 'role' => 'admin', 'status' => 'active'], 'phone = ?', [$adminPhone]);
                $adminId = (int) val('SELECT id FROM users WHERE phone = ?', [$adminPhone]);
            } else {
                $adminId = insert('users', ['name' => $adminName, 'phone' => $adminPhone, 'password_hash' => password_hash($adminPass, PASSWORD_DEFAULT),
                    'role' => 'admin', 'status' => 'active', 'hue' => 25, 'created_at' => now()]);
            }
            $general = default_settings()['general'];
            if (!empty($_POST['demo']) && !val('SELECT COUNT(*) FROM users WHERE is_demo = 1')) {
                seed_demo($adminId);
                $general['demoMode'] = true;
            }
            $general['siteNameFa'] = trim($_POST['site_name'] ?? '') ?: $general['siteNameFa'];
            save_setting('general', $general);
            if (!is_dir(__DIR__ . '/uploads')) @mkdir(__DIR__ . '/uploads', 0755, true);
            $done = true;
        }
    }
}
?>
<!doctype html>
<html lang="fa" dir="rtl">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex">
  <title>نصب بهیکس</title>
  <link rel="stylesheet" href="assets/css/style.css">
  <link rel="stylesheet" href="assets/css/pages.css">
  <style>
    .inst { max-width: 760px; margin: 40px auto; padding: 0 16px 60px; }
    .inst .card { padding: 28px; }
    .inst h1 { font-size: 1.6rem; font-weight: 900; }
    .inst h2 { font-size: 1.05rem; font-weight: 800; margin: 26px 0 12px; }
    .checks li { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px dashed var(--line); font-size: .9rem; }
    .err { padding: 12px 16px; border-radius: 14px; background: rgb(248 113 113 / .1); border: 1px solid rgb(248 113 113 / .4); margin-top: 16px; font-size: .9rem; line-height: 2; }
    pre { direction: ltr; text-align: left; overflow: auto; padding: 14px; border-radius: 12px; background: var(--inset); font-size: .8rem; }
  </style>
</head>
<body>
<div class="page-glow" aria-hidden="true"></div>
<main class="inst">
  <div class="card glow">
    <span class="logo logo--md"><span class="logo-a">BEHI</span><span class="logo-x">X</span></span>
    <h1 class="mt-2">نصب سایت بهیکس</h1>
<?php if ($locked && !$done): ?>
    <p class="muted lh mt-2">سایت قبلاً نصب شده است. برای امنیت بیشتر، فایل <code>install.php</code> را از هاست حذف کنید.</p>
    <p class="mt-2"><a class="btn btn-primary" href="index.html">رفتن به سایت</a></p>
<?php elseif ($done): ?>
    <div class="success" style="padding:20px 0">
      <span class="success-icon">✓</span>
      <h2>نصب با موفقیت انجام شد!</h2>
      <p class="muted lh">با شماره موبایل و رمزی که تعیین کردید وارد پنل مدیریت شوید.<br><b>مهم:</b> فایل <code>install.php</code> را از هاست حذف کنید.</p>
      <div class="cta-actions"><a class="btn btn-primary" href="auth.html?next=dashboard.html%23settings">ورود به پنل مدیریت</a><a class="btn btn-ghost" href="index.html">مشاهده سایت</a></div>
    </div>
<?php elseif ($manualConfig): ?>
    <div class="err">جداول ساخته شد اما فایل تنظیمات قابل نوشتن نبود. یک فایل با نام <code>config.php</code> در پوشه <code>api</code> بسازید، متن زیر را داخلش قرار دهید و این صفحه را دوباره ارسال کنید.</div>
    <pre><?= htmlspecialchars($manualConfig, ENT_QUOTES, 'UTF-8') ?></pre>
<?php else: ?>
    <p class="muted lh mt-1">ابتدا در cPanel از بخش <b>MySQL Database Wizard</b> یک پایگاه داده و کاربر بسازید (با دسترسی ALL PRIVILEGES)، سپس اطلاعات را این‌جا وارد کنید.</p>
    <h2>بررسی پیش‌نیازها</h2>
    <ul class="checks"><?php foreach ($checks as $label => $ok): ?><li><span><?= $label ?></span><b class="<?= $ok ? 'ok' : 'bad' ?>"><?= $ok ? '✓' : '✗' ?></b></li><?php endforeach; ?></ul>
    <?php if ($errors): ?><div class="err"><?= implode('<br>', $errors) ?></div><?php endif; ?>
    <form method="post" class="form-grid mt-2" autocomplete="off">
      <input type="hidden" name="t" value="<?= $_SESSION['inst'] ?>">
      <h2>پایگاه داده</h2>
      <div class="form-grid form-grid-2">
        <div class="field"><label class="field-label" for="db_host">هاست</label><input class="input" id="db_host" name="db_host" dir="ltr" value="<?= $v('db_host', 'localhost') ?>"></div>
        <div class="field"><label class="field-label" for="db_name">نام پایگاه داده</label><input class="input" id="db_name" name="db_name" dir="ltr" value="<?= $v('db_name') ?>" placeholder="cpaneluser_behix"></div>
        <div class="field"><label class="field-label" for="db_user">نام کاربری</label><input class="input" id="db_user" name="db_user" dir="ltr" value="<?= $v('db_user') ?>"></div>
        <div class="field"><label class="field-label" for="db_pass">رمز عبور</label><input class="input" id="db_pass" name="db_pass" type="password" dir="ltr"></div>
      </div>
      <h2>سایت و مدیر کل</h2>
      <div class="form-grid form-grid-2">
        <div class="field"><label class="field-label" for="site_name">نام فارسی سایت</label><input class="input" id="site_name" name="site_name" value="<?= $v('site_name', 'بهیکس') ?>"></div>
        <div class="field"><label class="field-label" for="url">آدرس سایت</label><input class="input" id="url" name="url" dir="ltr" value="<?= $v('url', $guessUrl) ?>"></div>
        <div class="field"><label class="field-label" for="admin_name">نام مدیر</label><input class="input" id="admin_name" name="admin_name" value="<?= $v('admin_name') ?>"></div>
        <div class="field"><label class="field-label" for="admin_phone">موبایل مدیر (نام کاربری)</label><input class="input" id="admin_phone" name="admin_phone" dir="ltr" value="<?= $v('admin_phone') ?>" placeholder="09xxxxxxxxx"></div>
        <div class="field"><label class="field-label" for="admin_pass">رمز مدیر (حداقل ۸ کاراکتر)</label><input class="input" id="admin_pass" name="admin_pass" type="password" dir="ltr"></div>
      </div>
      <label class="switch mt-2"><input type="checkbox" name="demo" value="1" <?= !empty($_POST["demo"]) ? "checked" : "" ?>><span class="track"></span>نصب داده‌های نمایشی (کاربران، سفارش‌ها و محصولات نمونه — بعداً از پنل قابل حذف است)</label>
      <button class="btn btn-primary mt-2" type="submit">نصب سایت</button>
    </form>
<?php endif; ?>
  </div>
</main>
</body>
</html>
